I have seen the light, and see that it is good.

diff --git a/bash_utils b/bash_utils
--- a/bash_utils
+++ b/bash_utils
@@ -1,60 +1,61 @@
 #!/usr/bin/env bash
 
 inTerm() {
-	[[ -t 0 || -p /dev/stdin ]]
+  [[ -t 0 || -p /dev/stdin ]]
 }
 
 isRunning() {
-	pgrep $1 &> /dev/null
+  pgrep $1
 }
 
 info() {
-	if inTerm; then
-		echo -e "\e[34m$1\e[0m" >&2
-	else
-		zenity --info --text="$*" &> /dev/null
-	fi
+  if inTerm; then
+    echo -e "\e[34m$1\e[0m" >&2
+  else
+    zenity --info --text="$*"
+  fi
 }
 
 err() {
-	if inTerm; then
-		echo -e "\e[31m$1\e[0m" >&2
-	else
-		zenity --error --text="$*" &> /dev/null
-	fi
+  if inTerm; then
+    echo -e "\e[31m$1\e[0m" >&2
+  else
+    zenity --error --text="$*"
+  fi
 }
 
 die() {
-	if [[ -n "$1" ]]; then
-		err "$1"
-	fi
-	exit 1
+  if [[ -n "$1" ]]; then
+    err "$1"
+  fi
+  # ! inTerm && exit 1
+  exit 1
 }
 
 has() {
-	verbose=false
-	if [[ $1 == '-v' ]]; then
-		verbose=true
-		shift
-	fi
-	if command -v "$1" &> /dev/null; then
-		return 0
-	else
-		[[ "$verbose" == true ]] && err "$1 not found"
-		return 1
-	fi
+  verbose=false
+  if [[ $1 == '-v' ]]; then
+    verbose=true
+    shift
+  fi
+  if command -v "$1" &> /dev/null; then
+    return 0
+  else
+    [[ "$verbose" == true ]] && err "$1 not found"
+    return 1
+  fi
 }
 
 ask() {
-	if inTerm; then
-		read -n1 -p "$* " ans
-		echo
-		if [[ ${ans^} == Y* ]]; then
-			return 0
-		else
-			return 1
-		fi
-	else
-		zenity --question --text="$@" 2> /dev/null
-	fi
+  if inTerm; then
+    read -n1 -p "$* " ans
+    echo
+    if [[ ${ans^} == Y* ]]; then
+      return 0
+    else
+      return 1
+    fi
+  else
+    zenity --question --text="$@"
+  fi
 }
diff --git a/local/bin/fzmp b/local/bin/fzmp
--- a/local/bin/fzmp
+++ b/local/bin/fzmp
@@ -1,47 +1,47 @@
 #!/usr/bin/env bash
 
 if [[ -e ${HOME}/.bash_utils ]]; then
-	source ${HOME}/.bash_utils
+  source ${HOME}/.bash_utils
 declare -a cmds
 
 else
-	echo -e "\e[31mbash_utils not found\e[0m" >&2
-	exit 1
+  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  exit 1
 fi
 
 declare player=''
 declare -a supported=( 'mpc' )
 
 for x in "${supported[@]}"; do
-	if has $x; then
-		player="$x"
-		break
-	fi
+  if has $x; then
+    player="$x"
+    break
+  fi
 done
 
 if [[ -z "$player" ]]; then
-	die "no supported music player found\n    fzmp currently supports: ${supported[*]}"
+  die "no supported music player found\n    fzmp currently supports: ${supported[*]}"
 fi
 
 if ! has fzf; then
-	die 'fzf not found'
+  die 'fzf not found'
 fi
 
 do_mpc() {
-	if ! isRunning mpd; then
-		die 'mpd not running'
-	fi
-	mapfile -t songs < <(mpc listall | sort -r | fzf --reverse -m -e +s)
-	if (( ${#songs[@]} > 0 )); then
-		printf '%s\n' "${songs[@]}" | mpc -q add
-		index=$(mpc playlist | wc -l)
-		if (( ${#songs[@]} > 1 )); then
-			index=$(( $index - ${#songs[@]} + 1))
-		fi
-		mpc -q play "$index"
-	fi
+  if ! isRunning mpd; then
+    die 'mpd not running'
+  fi
+  mapfile -t songs < <(mpc listall | sort -r | fzf --reverse -m -e +s)
+  if (( ${#songs[@]} > 0 )); then
+    printf '%s\n' "${songs[@]}" | mpc -q add
+    index=$(mpc playlist | wc -l)
+    if (( ${#songs[@]} > 1 )); then
+      index=$(( $index - ${#songs[@]} + 1))
+    fi
+    mpc -q play "$index"
+  fi
 }
 
 case "$player" in
-	'mpc') do_mpc ;;
+  'mpc') do_mpc ;;
 esac
diff --git a/local/bin/v b/local/bin/v
--- a/local/bin/v
+++ b/local/bin/v
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 
 if [[ -e ${HOME}/.bash_utils ]]; then
-	source ${HOME}/.bash_utils
+  source ${HOME}/.bash_utils
 else
-	echo -e "\e[31mbash_utils not found\e[0m" >&2
-	exit 1
+  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  exit 1
 fi
 
 usage() {
-	more <<'HELP'
+  more <<'HELP'
 v [OPTIONS] [FILES]
 create a new vim server or interact with an existing one
 
@@ -19,82 +19,81 @@ create a new vim server or interact with an existing one
 HELP
 }
 
+selectPane() {
+  serv="$1"
+  if [[ -n "$TMUX" && "$noselect" != true ]]; then
+    pane=$(vim --servername "$serv" --remote-expr '$TMUX_PANE')
+    if [[ -n "$pane" ]]; then
+      tmux select-pane   -t "$pane"
+      tmux select-window -t "$pane"
+    fi
+  fi &
+}
+
+startServer() {
+  serv="V_$(date +%s)"
+  if inTerm; then
+    if [[ "$noselect" != true && -n "$TMUX" ]]; then
+      tmux rename-window -t "$TMUX_PANE" 'vim'
+      if ! tmux list-sessions -F '#S' | grep 'cmd' &> /dev/null; then
+        tmux split-window -t "$TMUX_PANE" -d -v -p 25 'TMUX="" tmux new-session -s "cmd" \; source-file ${HOME}/dotfiles/tmux.alt.conf'
+      fi
+    fi &
+    exec vim --servername "$serv"  "$@"
+  else
+    if ! has gvim; then
+      die 'cannot start new vim server'
+    fi
+    exec gvim --servername "$serv"  "$@"
+  fi
+}
+
 declare noselect
 declare sendpane=false
 declare -a files
 declare -a vimopts
 
 while true; do
-	case "$1" in
-		'-h'|'--help') usage; exit 0 ;;
-		'-d') noselect=true; ;;
-		'-s') sendpane=true ;;
-		*) break ;;
-	esac
-	shift
+  case "$1" in
+    '-h'|'--help') usage; exit 0 ;;
+    '-d') noselect=true; ;;
+    '-s') sendpane=true ;;
+    *) break ;;
+  esac
+  shift
 done
-
-selectPane() {
-	serv="$1"
-	if [[ -n "$TMUX" && "$noselect" != true ]]; then
-		pane=$(vim --servername "$serv" --remote-expr '$TMUX_PANE')
-		if [[ -n "$pane" ]]; then
-			tmux select-pane   -t "$pane"
-			tmux select-window -t "$pane"
-		fi
-	fi &
-}
-
-startServer() {
-	serv="V_$(date +%s)"
-	if inTerm; then
-		if [[ "$noselect" != true && -n "$TMUX" ]]; then
-			tmux rename-window -t "$TMUX_PANE" 'vim'
-			if ! tmux list-sessions -F '#S' | silent grep 'cmd'; then
-				tmux split-window -t "$TMUX_PANE" -d -v -p 25 'TMUX="" tmux new-session -s "cmd" \; source-file ${HOME}/dotfiles/tmux.alt.conf'
-			fi
-		fi &
-		exec vim --servername "$serv"  "$@"
-	else
-		if ! has gvim; then
-			die 'cannot start new vim server'
-		fi
-		exec gvim --servername "$serv"  "$@"
-	fi
-}
 
 serv=$(vim --serverlist | grep -P '^V_[0-9]+$')
 if [[ -n "$serv" ]]; then
-	vimopts=( "--servername $serv" )
-	if (( $# == 0 )); then
-		if has fv; then
-			if inTerm; then
-				fv -c "v ${noselect:+-d}"
-				exit 0
-			else
-				x-terminal-emulator -e 'fv' '-c' 'v'
-			fi
-		else
-			die 'enter a file name or install fv'
-		fi
-	else
-		while (( $# > 0 )); do
-			case "$1" in
-				:*) vim --servername "$serv" --remote-send "<esc>$1<cr>" ;;
-				!*) vim --servername "$serv" --remote-send "${1:1}" ;;
-				+*) vim --servername "$serv" --remote-expr "${1:1}" ;;
-				http://* | https://* ) vim --servername "$serv" --remote-send "<esc>:enew | r !command curl -sL $1<cr><esc>ggdd:set ft=" ;;
-				*) files+=("$1") ;;
-			esac
-			shift
-		done
-	fi
-	selectPane "$serv"
-	for f in "${files[@]}"; do
-		# err "found file $f"
-		vim --servername "$serv" --remote "$f"
-		sleep 0.1
-	done
+  vimopts=( "--servername $serv" )
+  if (( $# == 0 )); then
+    ! has fv && die 'enter a file name or install fv'
+    if inTerm; then
+      # fv -c "v ${noselect:+-d}"
+      exit 0
+    else
+      x-terminal-emulator -e 'fv' '-c' 'v'
+    fi
+  else
+    while (( $# > 0 )); do
+      case "$1" in
+        :*) vim ${vimopts[*]} --remote-send "<esc>$1<cr>" ;;
+        !*) vim ${vimopts[*]} --remote-send "${1:1}" ;;
+        +*) vim ${vimopts[*]} --remote-expr "${1:1}" ;;
+        http://* | https://* ) vim ${vimopts[*]} --remote-send "<esc>:enew | r !command curl -sL $1<cr><esc>ggdd:set ft=" ;;
+        *) files+=("$1") ;;
+      esac
+      shift
+    done
+  fi
+  selectPane "$serv"
+  for f in "${files[@]}"; do
+    if [[ -d "$f" ]]; then
+      f=$(ag -lk)
+    fi
+    vim ${vimopts[*]} --remote "$f"
+    sleep 0.2
+  done
 else
-	startServer "$@"
+  startServer "$@"
 fi
