another bad commit message

diff --git a/bash_utils b/bash_utils
--- a/bash_utils
+++ b/bash_utils
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 
-esc=$(printf '\033')
-c_reset="${esc}[0m"
-c_red="${esc}[31m"
-c_green="${esc}[32m"
-c_blue="${esc}[34m"
+declare esc=$(printf '\033')
+declare c_reset="${esc}[0m"
+declare c_red="${esc}[31m"
+declare c_green="${esc}[32m"
+declare c_blue="${esc}[34m"
 
 inTerm() {
   [[ -t 0 || -p /dev/stdin ]]
@@ -36,40 +36,41 @@ die() {
 }
 
 has() {
-  verbose=false
+  local verbose=false
   if [[ $1 == '-v' ]]; then
     verbose=true
     shift
   fi
-  if command -v $1 &> /dev/null; then
-    return 0
-  else
-    [[ "$verbose" == true ]] && err "$1 not found"
-    return 1
-  fi
+  for c in "$@"; do c="${c%% *}"
+    if ! command -v "$c" &> /dev/null; then
+      [[ "$verbose" == true ]] && err "$c not found"
+      return 1
+    fi
+  done
 }
 
 ask() {
   if inTerm; then
-    read -n1 -p "$* " ans
+    read -r -n1 -p "$* " ans
     echo
     [[ ${ans^} == Y* ]]
   else
-    zenity --question --text="$@"
+    zenity --question --text="$*"
   fi
 }
 
 prompt() {
-  local opts=()
+  local opts=() one
   if [[ "$1" == '-1' ]]; then
     opts+=( '-n1' )
+    one=1
     shift
   fi
   if [[ "$1" == '-s' ]]; then
     opts+=( '-s' )
     shift
   fi
-  read -e -r ${opts[*]} -p "$@ " ans
+  read -e -r ${opts[*]} -p "$* " ans
   if [[ $one == '1' ]]; then
     echo
     [[ ${ans,} == y ]]
@@ -79,8 +80,8 @@ prompt() {
 }
 
 getCommandFallbacks() {
-  for arg in "$@"; do
-    if has $arg; then
+  for arg in "$@"; do arg="${arg%% *}"
+    if has "$arg"; then
       echo "$arg"
       return 0
     fi
diff --git a/local/bin/record b/local/bin/record
--- a/local/bin/record
+++ b/local/bin/record
@@ -43,19 +43,17 @@ getdimensions() {
     local xwininfo x y w h
     echo -ne 'click a window\r'
     xwininfo=$(xwininfo)
-    read x y w h < <(awk -F':' '/Absolute upper-left X/ { x=$2 }
-    /Absolute upper-left Y/ { y=$2 }
-    /Width/ { w=$2 }
-    /Height/ { h=$2 }
-    END { print x, y, w, h }' <<< "$xwininfo")
+    read -r x y w h < <(awk '/Absolute upper-left X/ { x=$2 }
+      /Absolute upper-left Y/ { y=$2 }
+      /Width/ { w=$2 }
+      /Height/ { h=$2 }
+      END { print x, y, w, h }' -F':' <<< "$xwininfo")
     dimensions=( ['x']="$x" ['y']="$y" ['w']="$w" ['h']="$h" )
   elif [[ "$region" == true ]]; then
-    if ! has xrectsel; then
-      die 'xrectsel required for -s'
-    fi
+    has xrectsel || die 'xrectsel required for -s'
     echo -ne 'select a region\r'
     #TODO: don't use eval
-    eval dimensions=( $(xrectsel "['x']='%x' ['y']='%y' ['w']='%w' ['h']='%h'") )
+    eval "dimensions=( $(xrectsel "['x']='%x' ['y']='%y' ['w']='%w' ['h']='%h'") )"
   else
     scrsize=$(xdpyinfo | awk '/dimensions/{print $2}')
     dimensions=( ['x']='0' ['y']='0' ['w']="${scrsize%%x*}" ['h']="${scrsize#*x}" )
@@ -103,9 +101,7 @@ while getopts "f:F:d:D:swh" opt; do
   esac
 done
 
-if [[ -z "$DISPLAY" ]]; then
-  die 'could not grab $DISPLAY'
-fi
+[[ -z "$DISPLAY" ]] && die 'could not grab DISPLAY'
 
 if [[ -f "$file" && "$overwrite" == false ]] && ! ask "overwrite ${file}? "; then
   die
