lots of tinkering and too lazy to document thoroughly

diff --git a/local/bin/fv b/local/bin/fv
--- a/local/bin/fv
+++ b/local/bin/fv
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
-source ~/.bash_utils
+if [[ -e ${HOME}/.bash_utils ]]; then
+	source ${HOME}/.bash_utils
+else
+	echo -e "\e[31mbash_utils not found\e[0m" >&2
+	exit 1
+fi
 
 usage() {
 	more <<'HELP'
@@ -16,14 +21,12 @@ setCmd() {
 	 if has $1; then
 		cmd="$1"
 	else
-		err "$1 is not a valid command"
-		exit 1
+		die "$1 is not a valid command"
 	fi
 }
 
 if ! has 'fzf'; then
-	err 'requires fzf installed'
-	exit 1
+	die 'requires fzf installed'
 fi
 
 cmd='vim'
diff --git a/local/bin/v b/local/bin/v
--- a/local/bin/v
+++ b/local/bin/v
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
-source ~/.bash_utils
+if [[ -e ${HOME}/.bash_utils ]]; then
+	source ${HOME}/.bash_utils
+else
+	echo -e "\e[31mbash_utils not found\e[0m" >&2
+	exit 1
+fi
 
 usage() {
 	more <<'HELP'
@@ -42,11 +47,11 @@ selectPane() {
 
 startServer() {
 	serv="V_$(date +%s)"
-	if [[ -t 0 ]]; then
+	if inTerm; then
 		if [[ "$noselect" != true && -n "$TMUX" ]]; then
 			tmux rename-window -t "$TMUX_PANE" 'vim'
-			if ! tmux list-sessions -F '#S' | grep 'cmd' &> /dev/null; then
-				tmux split-window -t "$TMUX_PANE" -d -v -p 25 'TMUX="" tmux new-session -s "cmd" \; source-file ~/dotfiles/tmux.alt.conf'
+			if ! tmux list-sessions -F '#S' | silent grep 'cmd'; then
+				tmux split-window -t "$TMUX_PANE" -d -v -p 25 'TMUX="" tmux new-session -s "cmd" \; source-file ${HOME}/dotfiles/tmux.alt.conf'
 			fi
 		fi &
 		exec vim --servername "$serv"  "$@"
@@ -63,7 +68,7 @@ if [[ -n "$serv" ]]; then
 	vimopts=( "--servername $serv" )
 	if (( $# == 0 )); then
 		if has fv; then
-			if [[ -t 0 ]]; then
+			if inTerm; then
 				fv -c "v ${noselect:+-d}"
 				exit 0
 			else
@@ -78,17 +83,18 @@ if [[ -n "$serv" ]]; then
 				:*) vim --servername "$serv" --remote-send "<esc>$1<cr>" ;;
 				!*) vim --servername "$serv" --remote-send "${1:1}" ;;
 				+*) vim --servername "$serv" --remote-expr "${1:1}" ;;
-				http://* | https://* ) vim --servername "$serv" --remote-send "<esc>:enew | r !command curl -skL $1<cr>" ;;
+				http://* | https://* ) vim --servername "$serv" --remote-send "<esc>:enew | r !command curl -sL $1<cr><esc>ggdd:set ft=" ;;
 				*) files+=("$1") ;;
 			esac
 			shift
 		done
 	fi
+	selectPane "$serv"
 	for f in "${files[@]}"; do
 		# err "found file $f"
 		vim --servername "$serv" --remote "$f"
+		sleep 0.1
 	done
-	selectPane "$serv"
 else
 	startServer "$@"
 fi
diff --git a/local/bin/x-editor b/local/bin/x-editor
--- a/local/bin/x-editor
+++ b/local/bin/x-editor
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
 
-source ~/.bash_utils
+if [[ -e ${HOME}/.bash_utils ]]; then
+	source ${HOME}/.bash_utils
+else
+	echo -e "\e[31mbash_utils not found\e[0m" >&2
+	exit 1
+fi
 
-declare -a cmds
-
-for x in 'v' 'vim'; do
+for x in 'v' 'gvim' 'vim'; do
 	if has "$x"; then
 		cmds=( "$x" "$@" )
 		break
@@ -12,3 +15,4 @@ for x in 'v' 'vim'; do
 done
 
 x-terminal-emulator -e ${cmds[*]}
+
diff --git a/local/bin/x-pdf b/local/bin/x-pdf
--- a/local/bin/x-pdf
+++ b/local/bin/x-pdf
@@ -1,9 +1,13 @@
 #!/usr/bin/env bash
 
-source ~/.bash_utils
+if [[ -e ${HOME}/.bash_utils ]]; then
+	source ${HOME}/.bash_utils
+else
+	echo -e "\e[31mbash_utils not found\e[0m" >&2
+	exit 1
+fi
 
-fav=( 'mupdf' 'zathura' 'apvlv' 'evince' )
-for x in "${fav[@]}"; do
+for x in 'mupdf' 'zathura' 'apvlv' 'evince'; do
 	if has "$x"; then
 		( exec "$x" "$@" ) &
 		break
diff --git a/local/bin/xmux b/local/bin/xmux
--- a/local/bin/xmux
+++ b/local/bin/xmux
@@ -1,10 +1,15 @@
 #!/usr/bin/env bash
 
-source ~/.bash_utils
+if [[ -e ${HOME}/.bash_utils ]]; then
+	source ${HOME}/.bash_utils
+else
+	echo -e "\e[31mbash_utils not found\e[0m" >&2
+	exit 1
+fi
 
 declare -a cmds
 
-if tmux ls; then
+if silent tmux ls; then
 	cmds=( 'tmux attach' )
 else
 	if has mux; then
@@ -14,5 +19,5 @@ else
 	fi
 fi
 
-
+xrdb -load ~/.Xresources
 x-terminal-emulator -e ${cmds[*]}
