I have seen the light, and see that it is good.

diff --git a/local/bin/fv b/local/bin/fv
--- a/local/bin/fv
+++ b/local/bin/fv
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 
 if [[ -e ${HOME}/.bash_utils ]]; then
-	source ${HOME}/.bash_utils
+  source ${HOME}/.bash_utils
 else
-	echo -e "\e[31mbash_utils not found\e[0m" >&2
-	exit 1
+  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  exit 1
 fi
 
 usage() {
-	more <<'HELP'
+  more <<'HELP'
 fv [OPTIONS] [SEARCH]
 fuzzy file filtering and command executing
 
@@ -18,15 +18,15 @@ HELP
 }
 
 setCmd() {
-	 if has $1; then
-		cmd="$1"
-	else
-		die "$1 is not a valid command"
-	fi
+   if has $1; then
+    cmd="$1"
+  else
+    die "$1 is not a valid command"
+  fi
 }
 
 if ! has 'fzf'; then
-	die 'requires fzf installed'
+  die 'requires fzf installed'
 fi
 
 cmd='vim'
@@ -37,96 +37,95 @@ searchopts=()
 allfiles=false
 
 while getopts "hac:" opt; do
-	case "$opt" in
-		h) usage; exit 0    ;;
-		a) allfiles=true     ;;
-		c) setCmd "$OPTARG" ;;
-	esac
+  case "$opt" in
+    h) usage; exit 0    ;;
+    a) allfiles=true     ;;
+    c) setCmd "$OPTARG" ;;
+  esac
 done
 shift "$((OPTIND-1))"
 
-if [[ "$cmd" == 'vim' && -n "$DISPLAY" ]] && has v; then
-	cmd='v'
+if [[ "$cmd" == 'vim' ]]; then
+  if [[ -n "$DISPLAY" ]] && has v; then
+    cmd='v'
+  elif has 'nvim'; then
+    cmd='nvim'
+  fi
 fi
 
-for c in 'ag' 'ack' 'grep'; do
-	if has "$c"; then
-		searchcmd="$c"
-		break
-	fi
+# for c in 'ag' 'ack' 'grep'; do
+for c in 'grep'; do
+  if has "$c"; then
+    searchcmd="$c"
+    break
+  fi
 done
 
-if [[ $searchcmd  == 'grep' ]]; then
-	err 'you should strongly consider installing ag or ack'
-	sleep .5
-fi
+# if [[ $searchcmd  == 'grep' ]]; then
+#   err 'you should strongly consider installing ag or ack'
+#   sleep .5
+# fi
 
 if [[ -n "$1" ]]; then
-	searchstr="$1";
-	shift
+  if [[ -d "$1" ]]; then
+    searchopts+=( "$1" )
+  else
+    searchstr="$1"
+  fi
+  shift
 fi
 
 case "$searchcmd" in
-	'ag')
-		searchopts+=( '-l' )
-		if [[ "$allfiles" == true ]]; then
-			searchopts+=( '-a' '--hidden' )
-			if [[ "$searchstr" == '' ]]; then
-				searchopts+=( '-g' '' )
-			fi
-		else
-			searchopts+=( '-t' )
-		fi
-		;;
-	'ack')
-		if [[ "$searchstr" == '' ]]; then
-			if [[ "$allfiles" == false ]]; then
-				searchopts+=( '-g' '^[^\.]' )
-			else
-				searchopts+=( '-f' )
-			fi
-		else
-			searchopts+=( '-l' )
-		# 	searchopts+=( '--match' )
-		fi
-		;;
-	'grep')
-		searchopts+=( '-l' '-r' )
-		if [[ "$allfiles" == false ]]; then
-			searchopts+=(
-				'--exclude-dir=bower_components'
-				'--exclude-dir=node_modules'
-				'--exclude-dir=.cvs'
-				'--exclude-dir=.git'
-				'--exclude-dir=.hg'
-				'--exclude-dir=.svn'
-				'-I' 
-			)
-		fi
-		if [[ "$searchstr" == '' ]]; then
-			searchopts+=("")
-		fi
-		;;
+  'ag')
+    searchopts+=( '--color' )
+    if [[ "$allfiles" == true ]]; then
+      searchopts+=( '-a' '--hidden' )
+    # else
+    #   searchopts+=( '-t' )
+    fi
+    if [[ "$searchstr" == '' ]]; then
+      searchopts+=( '-g' '' )
+    fi
+    ;;
+  'ack')
+    if [[ "$searchstr" == '' ]]; then
+      if [[ "$allfiles" == false ]]; then
+        searchopts+=( '-g' '^[^\.]' )
+      else
+        searchopts+=( '-f' )
+      fi
+    else
+      searchopts+=( '-l' )
+    #   searchopts+=( '--match' )
+    fi
+    ;;
+  'grep')
+    searchopts+=( '-l' '-r' '-I' )
+    if [[ "$allfiles" == false ]]; then
+      searchopts+=( '--exclude-dir=bower_components' )
+      searchopts+=( '--exclude-dir=node_modules' )
+      searchopts+=( '--exclude-dir=jspm_packages' )
+      searchopts+=( '--exclude-dir=.cvs' )
+      searchopts+=( '--exclude-dir=.git' )
+      searchopts+=( '--exclude-dir=.hg' )
+      searchopts+=( '--exclude-dir=.svn' )
+    fi
+    if [[ "$searchstr" == '' ]]; then
+      searchopts+=( '' )
+    fi
+    ;;
 esac
 
 if [[ "$searchstr" != '' ]]; then
-	searchopts+=( "$searchstr" )
+  searchopts+=( "$searchstr" )
 fi
 
 # err "$searchcmd ${searchopts[*]}" # verbose option?
-mapfile -t files < <("$searchcmd" "${searchopts[@]}" 2> /dev/null | fzf -e -m --reverse)
+mapfile -t files < <(command "$searchcmd" "${searchopts[@]}" 2> /dev/null | fzf -e -m --reverse --ansi)
 
 if [[ ${#files[@]} == 0 ]]; then
-	# err 'no files selected, exiting'
-	exit 0
-fi
-
-if [[ "$searchstr" != '' ]]; then
-	if [[ "$cmd" == 'vim' ]]; then
-		cmdopts+=( "+'/$searchstr'" )
-	elif [[ "$cmd" == 'v' ]]; then
-		( sleep 0.5 && v "!/$searchstr<cr>zv" ) &
-	fi
+  # err 'no files selected, exiting' # verbose option?
+  exit 0
 fi
 
 # err "$cmd ${cmdopts[@]} ${files[*]}" # verbose option?
diff --git a/local/bin/record b/local/bin/record
--- a/local/bin/record
+++ b/local/bin/record
@@ -1,121 +1,129 @@
 #!/usr/bin/env bash
 
 if [[ -e ${HOME}/.bash_utils ]]; then
-	source ${HOME}/.bash_utils
+  source ${HOME}/.bash_utils
 else
-	echo -e "\e[31mbash_utils not found\e[0m" >&2
-	exit 1
+  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  exit 1
 fi
 
-file="$(date +%F-%s).gif"
+file="$(date +%F-%s).webm"
 window=false
 region=false
 duration=10
 delay=0
+declare verbose
 declare -A dimensions
 
 usage() {
-	more <<'HELP'
+  more <<'HELP'
 'Usage: record [OPTIONS]
   -h  this help
-  -f  specify file name [defaults to $(date +%F-%s).gif]
+  -f  specify file name [defaults to "$(date +%F-%s).webm"]
   -F  specify file name and overwrite if exists
   -d  specify duration
   -D  specify delay
   -w  select window
-  -s  draw selectable region'
+  -s  draw selectable region
+  -v  show verbose output from ffmpeg'
 # -k  display keystrokes during recording
 HELP
 }
 
 delay() {
-	for (( i=delay; i>0; --i )) ; do
-		echo -ne "$i..             \r"
-		sleep 1
-	done
-	echo -ne 'recording                \r'
+  for (( i=delay; i>0; --i )) ; do
+    echo -ne "$i..                     \r"
+    sleep 1
+  done
+  echo -ne "recording                \r"
 }
 
 getdimensions() {
-	if [[ "$window" == true ]]; then
-		echo -ne 'click a window\r'
-		xwininfo=$(xwininfo)
-		read x y w h < <(awk -F':' '/Absolute upper-left X/ { x = $2 }
-		/Absolute upper-left Y/ { y = $2 }
-		/Width/ { w = $2 }
-		/Height/ { h = $2 }
-		END { print x, y, w, h }' <<< "$xwininfo")
-		dimensions=( ['x']="$x" ['y']="$y" ['w']="$w" ['h']="$h" )
-	elif [[ "$region" == true ]]; then
-		if ! has xrectsel; then
-			die 'xrectsel required for -s'
-		fi
-		echo -ne 'select a region\r'
-		#TODO: don't use eval
-		eval dimensions=( $(xrectsel "['x']='%x' ['y']='%y' ['w']='%w' ['h']='%h'") )
-	else
-		scrsize=$(xdpyinfo | awk '/dimensions/{print $2}')
-		dimensions=( ['x']='0' ['y']='0' ['w']="${scrsize%%x*}" ['h']="${scrsize#*x}" )
-	fi
+  if [[ "$window" == true ]]; then
+    echo -ne 'click a window\r'
+    xwininfo=$(xwininfo)
+    read x y w h < <(awk -F':' '/Absolute upper-left X/ { x=$2 }
+    /Absolute upper-left Y/ { y=$2 }
+    /Width/ { w=$2 }
+    /Height/ { h=$2 }
+    END { print x, y, w, h }' <<< "$xwininfo")
+    dimensions=( ['x']="$x" ['y']="$y" ['w']="$w" ['h']="$h" )
+  elif [[ "$region" == true ]]; then
+    if ! has xrectsel; then
+      die 'xrectsel required for -s'
+    fi
+    echo -ne 'select a region\r'
+    #TODO: don't use eval
+    eval dimensions=( $(xrectsel "['x']='%x' ['y']='%y' ['w']='%w' ['h']='%h'") )
+  else
+    scrsize=$(xdpyinfo | awk '/dimensions/{print $2}')
+    dimensions=( ['x']='0' ['y']='0' ['w']="${scrsize%%x*}" ['h']="${scrsize#*x}" )
+  fi
 }
 
-record() {
-	#TODO: maybe remove byzanz altogether in favor of plain ffmpeg?
-	case "$1" in
-		'byzanz')
-			byzanz-record \
-				--duration="$duration"\
-				--x="${dimensions['x']}"\
-				--y="${dimensions['y']}"\
-				--width="${dimensions['w']}"\
-				--height="${dimensions['h']}"\
-				"$file" ;;
-		'ffmpeg')
-			size="${dimensions['w']}x${dimensions['h']}"
-			offset=":0.0+${dimensions['x']},${dimensions['y']}"
-			ffmpeg -y -loglevel panic\
-				-f x11grab -s "$size" -i "$offset" -t "$duration"\
-				-c:v libvpx -crf 12 -s "$size" -b:v 1200k \
-				-preset fast \
-				-b 1000k -threads 4 \
-				-f webm "$file" ;;
-		*)
-			die 'how did I get here?'
-	esac
+record-byzanz() {
+  #TODO: maybe remove byzanz altogether in favor of plain ffmpeg?
+  byzanz-record \
+    --duration="$duration"\
+    --x="${dimensions['x']}"\
+    --y="${dimensions['y']}"\
+    --width="${dimensions['w']}"\
+    --height="${dimensions['h']}"\
+    "$file" &&
+  echo "saved as $file"
+}
+
+record-ffmpeg() {
+  if [[ -z $verbose ]]; then
+    loglevel='panic'
+  else
+    loglevel='info'
+  fi
+  size="${dimensions['w']}x${dimensions['h']}"
+  offset="${DISPLAY}.0+${dimensions['x']},${dimensions['y']}"
+  ffmpeg -y -loglevel "${loglevel}" -f x11grab -s "$size" -i "$offset" -t "$duration" \
+    -c:v libvpx -crf 12 -s "$size" -b:v 1200k \
+    -preset veryslow \
+    -b 1000k -threads 4 \
+    -f webm "$file" &&
+  echo "saved as $file"
 }
 
 OPTERR=0
 while getopts "f:F:d:D:swh" opt; do
-	case "$opt" in
-		f) file="$OPTARG"; overwrite=false ;;
-		F) file="$OPTARG"; overwrite=true ;;
-		w) window=true; region=false ;;
-		s) window=false; region=true ;;
-		d) duration="$OPTARG" ;;
-		D) delay="$OPTARG" ;;
-	#	k) screenkeys=true ;;
-		h) usage; exit 0 ;;
-	esac
+  case "$opt" in
+    f) file="$OPTARG"; overwrite=false ;;
+    F) file="$OPTARG"; overwrite=true ;;
+    w) window=true; region=false ;;
+    s) window=false; region=true ;;
+    v) verbose=true ;;
+    d) duration="$OPTARG" ;;
+    D) delay="$OPTARG" ;;
+  #  k) screenkeys=true ;;
+    h) usage; exit 0 ;;
+  esac
 done
 
-case "$file" in
-	*gif)
-		if ! has byzanz-record; then
-			die 'need byzanz-record for recording gifs'
-		fi
-		cmd='byzanz' ;;
-	*webm)
-		if ! has ffmpeg; then
-			die 'need ffmpeg for recording webms'
-		fi
-		cmd='ffmpeg' ;;
-	*) die 'unknown file type, must be gif or webm' ;;
-esac
+if [[ -z "$DISPLAY" ]]; then
+  die 'could not grab $DISPLAY'
+fi
 
-if [[ -f "$file" && "$overwrite" == false ]] && ! prompt "overwrite ${file}? "; then
-	die
+if [[ -f "$file" && "$overwrite" == false ]] && ! ask "overwrite ${file}? "; then
+  die
 fi
 
 getdimensions
 delay
-record "$cmd"
+case "$file" in
+  *gif)
+    if ! has byzanz-record; then
+      die 'need byzanz-record for recording gifs'
+    fi
+    record-byzanz ;;
+  *webm)
+    if ! has ffmpeg; then
+      die 'need ffmpeg for recording webms'
+    fi
+    record-ffmpeg ;;
+  *) die 'unknown file type, must be gif or webm' ;;
+esac
diff --git a/local/bin/x-www-browser b/local/bin/x-www-browser
--- a/local/bin/x-www-browser
+++ b/local/bin/x-www-browser
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
 
 if [[ -e ${HOME}/.bash_utils ]]; then
-	source ${HOME}/.bash_utils
+  source ${HOME}/.bash_utils
 else
-	echo -e "\e[31mbash_utils not found\e[0m" >&2
-	exit 1
+  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  exit 1
 fi
 
 for x in 'firefox' 'luakit'; do
-	if has "$x"; then
-		( exec "$x" "$@" ) &
-		break
-	fi
+  if has "$x"; then
+    ( exec "$x" "$@" ) &
+    break
+  fi
 done
