i hate commit messages

diff --git a/local/bin/passgen b/local/bin/passgen
--- a/local/bin/passgen
+++ b/local/bin/passgen
@@ -3,7 +3,7 @@
 if [[ -e "${HOME}/.bash_utils" ]]; then
   source "${HOME}/.bash_utils"
 else
-  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  printf '\e[31mbash_utils not found\e[0m\n' >&2
   exit 1
 fi
 
@@ -17,10 +17,10 @@ declare charrange='[a-zA-Z0-9]'
 OPTERR=0
 while getopts "w:c:m:r:" opt; do
   case "$opt" in
-    w) words="$(printf '%d' "$OPTARG")" ;;
-    c) chars="$(printf '%d' "$OPTARG")" ;;
-    m) maxlength="$(printf '%d' "$OPTARG")" ;;
-    r) charrange="$(printf '%s' "$OPTARG")" ;;
+    w) words=$(printf '%d' "$OPTARG") ;;
+    c) chars=$(printf '%d' "$OPTARG") ;;
+    m) maxlength=$(printf '%d' "$OPTARG") ;;
+    r) charrange=$(printf '%s' "$OPTARG") ;;
   esac
 done
 shift "$((OPTIND-1))"
@@ -35,12 +35,12 @@ words() {
   else
     str=$(shuf /usr/share/cracklib/cracklib-small | head -n "$1")
   fi
-  str=$(sed -r "s/'\w\b//g; s/\b(.)/\u\1/g" <<< "$str" | tr -d '\n ')
-  echo "$str"
+  str=$(sed -r "s/'(\w)\b/\1/g; s/\b(.)/\u\1/g; s/ //g" <<< "$str")
+  printf '%s\n' "$str"
 }
 
 chars() {
-  echo "$(grep -a -oP "$charrange" < /dev/urandom | tr -d '\n' | head -c "$1")"
+  printf '%s\n' "$(grep -a -oP "$charrange" < /dev/urandom | tr -d '\n' | head -c "$1")"
 }
 
 if (( words > 0)); then
diff --git a/local/bin/v b/local/bin/v
--- a/local/bin/v
+++ b/local/bin/v
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
-if [[ -e ${HOME}/.bash_utils ]]; then
-  source ${HOME}/.bash_utils
+if [[ -e "${HOME}/.bash_utils" ]]; then
+  source "${HOME}/.bash_utils"
 else
-  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  printf '\e[31mbash_utils not found\e[0m\n' >&2
   exit 1
 fi
 
@@ -49,7 +49,6 @@ startServer() {
 }
 
 declare noselect
-declare sendpane=false
 declare -a files
 declare -a vimopts
 
@@ -57,15 +56,14 @@ while true; do
   case "$1" in
     -h|--help) usage; exit 0 ;;
     -d) noselect=true; ;;
-    -s) sendpane=true ;;
     *) break ;;
   esac
   shift
 done
 
-serv=$(vim --serverlist | grep -P '^V_[0-9]+$')
+serv=$(vim --serverlist | grep -oP '^V_\d+$')
 if [[ -n "$serv" ]]; then
-  vimopts=( "--servername $serv" )
+  vimopts=( '--servername' "$serv" )
   if (( $# == 0 )); then
     ! has fv && die 'enter a file name or install fv'
     if inTerm; then
@@ -77,10 +75,10 @@ if [[ -n "$serv" ]]; then
   else
     while (( $# > 0 )); do
       case "$1" in
-        :*) vim ${vimopts[*]} --remote-send "<esc>$1<cr>" ;;
-        !*) vim ${vimopts[*]} --remote-send "${1:1}" ;;
-        +*) vim ${vimopts[*]} --remote-expr "${1:1}" ;;
-        http://* | https://* ) vim ${vimopts[*]} --remote-send "<esc>:enew | r !command curl -sL $1<cr><esc>ggdd:set ft=" ;;
+        :*) vim "${vimopts[@]}" --remote-send "<esc>$1<cr>" ;;
+        !*) vim "${vimopts[@]}" --remote-send "${1:1}" ;;
+        +*) vim "${vimopts[@]}" --remote-expr "${1:1}" ;;
+        http://* | https://* ) vim "${vimopts[@]}" --remote-send "<esc>:enew | r !command curl -sL $1<cr><esc>ggdd:set ft=" ;;
         *) files+=("$1") ;;
       esac
       shift
@@ -91,7 +89,7 @@ if [[ -n "$serv" ]]; then
     if [[ -d "$f" ]]; then
       f=$(ag -lk)
     fi
-    vim ${vimopts[*]} --remote "$f"
+    vim "${vimopts[@]}" --remote "$f"
     sleep 0.2
   done
 else
diff --git a/local/bin/vimpipe b/local/bin/vimpipe
--- a/local/bin/vimpipe
+++ b/local/bin/vimpipe
@@ -3,13 +3,12 @@
 if [[ -e "${HOME}/.bash_utils" ]]; then
   source "${HOME}/.bash_utils"
 else
-  echo -e "\e[31m~/.bash_utils does not exist\e[0m" >&2
+  printf '\e[31mbash_utils not found\e[0m\n' >&2
   exit 1
 fi
 
 declare -a args
 declare file
-declare inplace
 
 OPTERR=0
 while getopts ":n:" opt; do
@@ -42,7 +41,7 @@ done
  args+=(-c 'w! /dev/fd/3 | q!')
 # fi
 
-( (vim ${file:--} -esnb -c 'norm gg0' "${args[@]}" >/dev/null 2>&1) 3>&1)
+( (vim "${file:--}" -esnb -c 'norm gg0' "${args[@]}" >/dev/null 2>&1) 3>&1)
 
 # if [[ -n "$file" && -n "$inplace" ]]; then
 #   diff -u orig new
diff --git a/local/bin/x-editor b/local/bin/x-editor
--- a/local/bin/x-editor
+++ b/local/bin/x-editor
@@ -1,17 +1,16 @@
 #!/usr/bin/env bash
 
-if [[ -e ${HOME}/.bash_utils ]]; then
-  source ${HOME}/.bash_utils
+if [[ -e "${HOME}/.bash_utils" ]]; then
+  source "${HOME}/.bash_utils"
 else
-  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  printf '\e[31mbash_utils not found\e[0m\n' >&2
   exit 1
 fi
 
 favs=('v' 'gvim' 'vim' 'emacs' 'vi' 'nano')
-cmd=$(select-from "${favs[@]}") || die "no editor found in ( ${favs[*]} )"
-editor="$cmd $*"
+editor=$(select-from "${favs[@]}") || die "no editor found in ( ${favs[*]} )"
 if inTerm; then
-  exec $editor
+  exec "$editor" "$@"
 else
-  ( exec x-terminal-emulator -e bash $editor) &
+  ( exec x-terminal-emulator -e bash "$editor" $* &)
 fi
