i suck at gig

diff --git a/local/bin/screenlock b/local/bin/screenlock
--- a/local/bin/screenlock
+++ b/local/bin/screenlock
@@ -1,9 +1,16 @@
-#!/bin/bash
-if has xscreensaver-command; then
-  screensaver-command --lock
+#!/usr/bin/env bash
+
+if [[ -e ${HOME}/.bash_utils ]]; then
+  source ${HOME}/.bash_utils
+else
+  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  exit 1
 fi
-sleep 1
-xset dpms force off
+
+has xscreensaver-command && screensaver-command --lock
 if [[ "$1" == '--suspend' ]]; then
   sudo pm-suspend
+else
+  sleep 1
+  xset dpms force off
 fi
