still suck at git

diff --git a/local/bin/wifi b/local/bin/wifi
--- a/local/bin/wifi
+++ b/local/bin/wifi
@@ -21,17 +21,17 @@ ask() {
 }
 
 has() {
-  verbose=false
+  local verbose=false
   if [[ $1 == '-v' ]]; then
     verbose=true
     shift
   fi
-  if command -v "$1" &> /dev/null; then
-    return 0
-  else
-    [[ "$verbose" == true ]] && err "$1 not found"
-    return 1
-  fi
+  for c in "$@"; do c="${c%% *}"
+    if ! command -v "$c" &> /dev/null; then
+      [[ "$verbose" == true ]] && err "$c not found"
+      return 1
+    fi
+  done
 }
 
 err() {
