really bad commit message

diff --git a/local/bin/xmux b/local/bin/xmux
--- a/local/bin/xmux
+++ b/local/bin/xmux
@@ -1,23 +1,27 @@
 #!/usr/bin/env bash
 
 if [[ -e ${HOME}/.bash_utils ]]; then
-	source ${HOME}/.bash_utils
+  source ${HOME}/.bash_utils
 else
-	echo -e "\e[31mbash_utils not found\e[0m" >&2
-	exit 1
+  echo -e "\e[31mbash_utils not found\e[0m" >&2
+  exit 1
 fi
 
 declare -a cmds
 
-if tmux ls; then
-	cmds=( 'tmux attach' )
+if tmux ls &> /dev/null; then
+  cmds=( tmux attach )
 else
-	if has mux; then
-		cmds=( 'mux start main' )
-	else
-		cmds=( 'tmux' )
-	fi
+  if has tmuxinator; then
+    cmds=( tmuxinator start main )
+  else
+    cmds=( tmux )
+  fi
 fi
 
 xrdb -load ~/.Xresources
-x-terminal-emulator -e ${cmds[*]}
+if inTerm; then
+  exec ${cmds[*]}
+else
+  exec x-terminal-emulator -e ${cmds[*]}
+fi
